### ISSUE TITLE
Gradle build issue

### ISSUE THREAD

**Issue by mishraaditya595** [MgeeeeK/WritoText#3]
I just tried to build the app in my android studio and got this error. Can you help to fix it out?

FAILURE: Build failed with an exception.

* What went wrong:
The library com.google.android.gms:play-services-vision-common is being requested by various other libraries at [[19.1.0,19.1.0], [19.0.2,19.0.2]], but resolves to 19.1.0. Disable the plugin and check your dependencies tree using ./gradlew :app:dependencies.

**Comment by MgeeeeK** [comment]
oh lol just saw this, but thnx for reaching out... idk why tf i didn't upload all project files, this doesnt even have all the features I developed like RCNN model and support for clubbing multiple scans. Anyways, unfortunately, the project files are now lost  :'( cos my old laptop is long-dead.
